# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 314e2ef706e171c8294eab208e129c57dc5f017c65286dad3d5604eefeeb45343bae9655a035b9f84337514605173798e4c3ed43a2dca1767fb74c05af05aede

test:
  secret_key_base: a5d8c02485d8ac440e91d944e21390232627e403b8eb6146102f4770397bed5583da4c1ef05e07283a0e03d7687a2d714157e49c52f1caf620929cce0d9a4fd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
